### ISSUE TITLE
Add a Supplies tracker to the Equipment tab

### ISSUE THREAD

**Issue by Rangertheman** [Rangertheman/fwrpg-for-pbta#1]
![Supplies tracker](https://github.com/Rangertheman/fwrpg-for-pbta/assets/81484515/a01b3974-996e-4f46-b22e-1c448211b03f)

**Comment by brunocalado** [comment]
The easier way is just add this to the main tab.

**Comment by Rangertheman** [comment]
This will be added in the next version of the module.
