### ISSUE TITLE
PT-BR Translation

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#10]
Hi. This is the pt-BR translation. Thank you.

{
      "lang": "pt-BR",
      "name": "Português (Brasil)",
      "path": "lang/pt-BR.json"
}

[pt-BR.json](https://github.com/user-attachments/files/15551645/pt-BR.json)

**Comment by Rangertheman** [comment]
Thank you so very much!

The language file will be added to the next version.

**Comment by Rangertheman** [comment]
I have added a couple of labels for the Supply Tracker and for the Growth Options. Would you mind translating those? Thank you in advance! 
[pt-BR.json](https://github.com/user-attachments/files/15753885/pt-BR.json)

**Comment by brunocalado** [comment]
Done
[pt-BR.json](https://github.com/user-attachments/files/15754243/pt-BR.json)

**Comment by Rangertheman** [comment]
Thanks a ton!!

**Comment by Rangertheman** [comment]
The move type labels have change. Do you mind translating them? Thank you in advance! :)

[pt-BR.json](https://github.com/user-attachments/files/15778241/pt-BR.json)

**Comment by Rangertheman** [comment]
@brunocalado

**Comment by brunocalado** [comment]
Done
[pt-BR.json](https://github.com/user-attachments/files/15780030/pt-BR.json)

**Comment by Rangertheman** [comment]
Phenomenal! Thank you very much!
