### ISSUE TITLE
Replace ADVENTURING: Restock (Knowing) by Ask

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#11]
You can use use Knowing or intense, so would be better to change this move to Ask.

![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/1734c8a7-52e1-4ac1-a56d-372961ff4914)

**Comment by Rangertheman** [comment]
Thanks for the suggestion! This has been changed to "Ask" and will be added in the next version.
