### ISSUE TITLE
Change Growth Bar

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#14]
I suggest changing the "growth" section as shown in the image below. It can then be moved to the sidebar due to its size. This makes it easier to track the character's progress and understand their development.

![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/ac72021c-809f-4e0c-8d18-c54bf84a30c9)

**Comment by Rangertheman** [comment]
Excellent idea! This will be added in the next version.

**Comment by brunocalado** [comment]
> Excellent idea! This will be added in the next version.

I think you need both bars. Because you need to mark how much Growth you have and also what you did with your growth. 

Also, the book says the growth bar can reach 12.

**Comment by Rangertheman** [comment]
Both items will be present :) 

I tried changing it to 12 Growth, but it looks wonky next to the 10 Expedience points.

![Growth](https://github.com/Rangertheman/fwrpg-for-pbta/assets/81484515/1b0978be-21c1-4924-aba0-93490f3a37f3)
