### ISSUE TITLE
Change Manifest compatibility

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#15]
The module is not marked as compatible with the Foundry version because new versions are released all the time. You can make the following change to indicate that the module is compatible with Foundry version 12.

![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/42340a93-5301-4200-8c89-5d43ef15c283)

Replace:
```
   "compatibility":{
      "minimum":"11",
      "verified":"12.325"
   },
```
By:
```
   "compatibility":{
      "minimum":"11",
      "verified":"12"
   },
```

Also, remove `"verified":"0.9.8"` would be also be nice to show the compatibility and don't have to update all the time.
         {
            "id":"pbta",
            "type":"system",
            "manifest":"https://asacolips-artifacts.s3.amazonaws.com/pbta/0.9.7/system.json",
            "compatibility":{
               "minimum":"0.9.7",
               "verified":"0.9.8"
            }
         }

**Comment by Rangertheman** [comment]
Very good suggestions! Thanks! The compatibility information will be updated in next version.
