### ISSUE TITLE
Rename Last Breath

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#16]
Hi.

The  Last Breath is called epilogue in the book, Can you rename it?

Thank you
![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/d1619269-b0fc-4d71-a122-d95b3b4f8fd4)

![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/14cdcfc9-6528-4d2b-a26f-baa7dd774a98)

**Comment by Rangertheman** [comment]
Thank you for all your suggestions! Last Breath has been corrected to Epilogue, and will be updated in the next version.
