### ISSUE TITLE
Remove Move Type

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#17]
I think it will be more clear if the move type is removed. 

Replace
![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/8411786d-424c-4ec9-93f9-cdfeaefb045f)

By
![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/b4367e04-a687-4250-a064-d232db8f3966)

Thank you.

**Comment by brunocalado** [comment]
A suggestion: 

![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/bf70a6f8-147b-49d7-9b75-4315a3b20a4d)

**Comment by Rangertheman** [comment]
Very good suggestion, and I fully agree! I removed the move type. I will test out your second suggestion and see how it looks. One or both of these suggestions will be added to the next version.
