### ISSUE TITLE
Add Starting Moves to Item Grants

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#18]
I suggest putting the initial moves in the item grants field, so that when the class is placed on the sheet, the items are already on the sheet.

![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/1909dc22-4efe-43d2-8349-fa3a72454fac)

**Comment by Rangertheman** [comment]
This was being worked on and will be added to the next version :)
