### ISSUE TITLE
Missing Moves in a new Actor Sheet

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#19]
When you create a new actor sheet, some moves are not added.

![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/9c82f8bf-55f3-4242-bd95-846286fc1fb5)

**Comment by Rangertheman** [comment]
Thanks for noticing! The missing moves now have the correct type and will be added upon character creation. The correction will be made in the next version.
