### ISSUE TITLE
Improved Background Image

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#21]
Hi. I upscaled the image for a better scene. I also added a torch to the scene.

Scene:
[fvtt-Scene-fantasy-world-rpg-ZG4i7fQfUKPWxhhM.json](https://github.com/user-attachments/files/15795254/fvtt-Scene-fantasy-world-rpg-ZG4i7fQfUKPWxhhM.json)

Image:
[Map_logo.zip](https://github.com/user-attachments/files/15795258/Map_logo.zip)

Preview

https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/7e205deb-8dc2-4440-bcf5-606e6e85e1eb

**Comment by Rangertheman** [comment]
Thank you very much for the upgraded image! The new and improved background has been added in version 0.4.1.
