### ISSUE TITLE
Missing Text Lead The Flock

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#25]
![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/e69ef5fc-c7e8-45b7-8df3-8954937fda55)
![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/0a07dc42-9642-466f-a6ba-e214fe1d13e5)

**Comment by Rangertheman** [comment]
Thanks for letting me know! The text is added in version 0.4.1.
