### ISSUE TITLE
Add Compediums to a Folder

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#27]
You can add all compediums to a single folder. This make the world more organized.

Just add this to the manifest.json.

  "packFolders": [
    {
      "name": "Fantasy World RPG",
      "sorting": "a",
      "color": "#5987bb",
      "packs": [
        "common-moves",
        "class-descriptions",
        "captain-moves",
        "knight-moves",
        "occultist-moves",
        "priest-moves",
        "veteran-moves",
        "wildcaller-moves",
        "maker-moves",
        "wayfarer-moves",
        "troubadour-moves",
        "scoundrel-moves",
        "fantasy-world-srd",
        "fantasy-world-srd-ita",
        "fantasy-world-background"            
      ],
      "folders": []
    }
  ]

**Comment by brunocalado** [comment]
You can change the color with "color": "#5987bb",

**Comment by Rangertheman** [comment]
Thanks!! I agree, it looks more organized with the folder. 

I like the light blue that was suggested in your first comment :)

This change is implemented in version 0.4.1.
