### ISSUE TITLE
PBTA Manifest Gets Outdated

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#28]
You are using:
     "manifest":"https://asacolips-artifacts.s3.amazonaws.com/pbta/1.0.7/system.json",
For the PBTA system requirement, this will always be outdated. 

Try to replace by
https://asacolips-artifacts.s3.amazonaws.com/pbta/latest/system.json

**Comment by Rangertheman** [comment]
Thanks for the suggestion! I have changd the link in version 0.4.1.
