### ISSUE TITLE
PBTA 1.0.12 Broke Agents Actor Sheet

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#29]
After update to PBTA 1.0.12 the Agents actor sheet is now broken.

Before update
![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/8d77ade2-49ab-4805-b29d-c1c2731258d5)

After update
![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/58f0123a-b2a6-48e0-a984-7dbce43c1002)

**Comment by Rangertheman** [comment]
Version 0.4.1 has fixed both the Protagonist- and Agent Sheets. 

(A variable was changed in system update 1.0.10 that messed up the sheets)
