### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#3]
Hi. Thank you for the module.

There is some broken links. 
![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/653b4c7c-7e70-4465-9c2e-ec4e15afa978)

You can fix this dragging from the compedium.

https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/dd6d56e6-e196-4e41-8ae8-9e92676b83aa

**Comment by Rangertheman** [comment]
Thank you for your suggestion! A very good one!

Long Rest, Journey and End of Session will get links to the appropriate section in the SRD journal in the next update.
