### ISSUE TITLE
SPECIAL: Last Breath add box

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#4]
Hi. Can you add new checkboxes to the sidebar, so the palyer can check the last breath options to  make easy to register this? Tks

![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/afb5e8db-749c-4d37-8556-bcd9f01b7192)

**Comment by Rangertheman** [comment]
Thank you for your suggestion! :) 

For now, the player will be prompted before the roll to add the number of +OPTIONS they selected. The same functionality has been added to Long Rest and to the Occultist's Arcana Unearthed move.

I might change this to some sort of checkboxes in a future update.

**Comment by brunocalado** [comment]
> Thank you for your suggestion! :)
> 
> For now, the player will be prompted before the roll to add the number of +OPTIONS they selected. The same functionality has been added to Long Rest and to the Occultist's Arcana Unearthed move.
> 
> I might change this to some sort of checkboxes in a future update.

To play AMW I created a attribute for bond. So, when the PCs need to roll it, they use the attribute by default. This is another solution.
