### ISSUE TITLE
Broken Link: Familiar

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#6]
![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/8227439c-c541-44fa-b91b-53c7cda6deeb)

**Comment by Rangertheman** [comment]
This should be fixed in 0.3.4

**Comment by Rangertheman** [comment]
I need to look into this some more.

**Comment by Rangertheman** [comment]
Will be fixed in the next version.
