### ISSUE TITLE
I Can't Roll on v12

### ISSUE THREAD

**Issue by brunocalado** [Rangertheman/fwrpg-for-pbta#7]
If I try to roll dice I got an error:
<html>
<body>
<div class="console-message repeated-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 4px; flex: 1 1 auto; display: flex; color: rgb(227, 227, 227); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 0%; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label="actor.js:231 Uncaught (in promise) TypeError: Cannot destructure property 'modifier' of 'game.pbta.sheetConfig.statToggle' as it is undefined.
    at ActorPbta._getStatFormula (actor.js:231:11)
    at ActorPbta._onRollStat (actor.js:180:24)
    at ActorPbta._onRoll (actor.js:169:20)
    at PbtaActorSheet._onRollable (actor-sheet.js:661:14)
    at HTMLLabelElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006) Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://164.152.33.142:30000/systems/src/module/documents/actor.js:231" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">actor.js:231</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><div style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot destructure property 'modifier' of 'game.pbta.sheetConfig.statToggle' as it is undefined.
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at ActorPbta._getStatFormula (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://164.152.33.142:30000/systems/src/module/documents/actor.js:231:11" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">actor.js:231:11</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at ActorPbta._onRollStat (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://164.152.33.142:30000/systems/src/module/documents/actor.js:180:24" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">actor.js:180:24</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at ActorPbta._onRoll (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://164.152.33.142:30000/systems/src/module/documents/actor.js:169:20" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">actor.js:169:20</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at PbtaActorSheet._onRollable (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://164.152.33.142:30000/systems/src/module/applications/actor/actor-sheet.js:661:14" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">actor-sheet.js:661:14</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at HTMLLabelElement.dispatch (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://164.152.33.142:30000/scripts/jquery.min.js:2:40035" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">jquery.min.js:2:40035</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at v.handle (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://164.152.33.142:30000/scripts/jquery.min.js:2:38006" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">jquery.min.js:2:38006</button>)</span></div></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: monospace; --source-code-font-size: 12px; --source-code-font-family: monospace; width: 495.938px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | _getStatFormula | @ | actor.js:231
-- | -- | -- | --
  | _onRollStat | @ | actor.js:180
  | _onRoll | @ | actor.js:169
  | _onRollable | @ | actor-sheet.js:661
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2
  | await in v.handle (async) |   |  
  | _onRollable | @ | actor-sheet.js:661
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2

</span></div></div></div></div><button class="hover-button" aria-label="Understand this error" tabindex="0" style="box-sizing: border-box; min-width: var(--width); min-height: var(--width); font-family: var(--default-font-family); font-size: inherit; --width: 24px; align-items: center; background-color: var(--sys-color-cdt-base-container); border-radius: 50%; border: none; box-shadow: rgba(0, 0, 0, 0.15) 0px 1px 3px 1px, rgba(0, 0, 0, 0.3) 0px 1px 2px 0px; color: var(--sys-color-primary); height: var(--width); justify-content: center; margin: 0px; max-height: var(--width); max-width: var(--width); overflow: hidden; padding: 4px 3px 4px 5px; position: absolute; right: 6px; display: block; width: var(--width); orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><devtools-icon role="presentation" name="lightbulb-spark" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 16px; height: 16px; color: var(--sys-color-primary); vertical-align: sub; position: relative; box-sizing: border-box; min-width: 16px; min-height: 16px;"><br class="Apple-interchange-newline">
</body>
</html>

![image](https://github.com/Rangertheman/fwrpg-for-pbta/assets/4999783/bb70c53e-8e29-4ecf-8859-645e03881440)

**Comment by Rangertheman** [comment]
This has been fixed in the Powered by the Apocalypse system version 1.0.2
